/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TAlert {
    'close'?: string;
    'customClass'?: string;
    'icon'?: string;
    'open': () => Promise<void>;
    'opened': boolean;
    'size'?: string;
    'theme'?: string;
    'timeout'?: number;
    'title': string;
    'variant'?: string;
    'withTimeout'?: boolean;
  }
  interface TButton {
    /**
    * (optional) Deselected button
    */
    'deselected'?: boolean;
    /**
    * (optional) Disabled button
    */
    'disabled'?: boolean;
    /**
    * (optional) Button size
    */
    'size'?: string;
    /**
    * (optional) Button theme
    */
    'theme'?: string;
    /**
    * (optional) Button variant
    */
    'variant'?: string;
  }
  interface TCard {
    'deselected'?: boolean;
    'disabled'?: boolean;
    'size'?: string;
    'theme'?: string;
    'variant'?: string;
  }
}

declare global {


  interface HTMLTAlertElement extends Components.TAlert, HTMLStencilElement {}
  var HTMLTAlertElement: {
    prototype: HTMLTAlertElement;
    new (): HTMLTAlertElement;
  };

  interface HTMLTButtonElement extends Components.TButton, HTMLStencilElement {}
  var HTMLTButtonElement: {
    prototype: HTMLTButtonElement;
    new (): HTMLTButtonElement;
  };

  interface HTMLTCardElement extends Components.TCard, HTMLStencilElement {}
  var HTMLTCardElement: {
    prototype: HTMLTCardElement;
    new (): HTMLTCardElement;
  };
  interface HTMLElementTagNameMap {
    't-alert': HTMLTAlertElement;
    't-button': HTMLTButtonElement;
    't-card': HTMLTCardElement;
  }
}

declare namespace LocalJSX {
  interface TAlert extends JSXBase.HTMLAttributes<HTMLTAlertElement> {
    'close'?: string;
    'customClass'?: string;
    'icon'?: string;
    'opened'?: boolean;
    'size'?: string;
    'theme'?: string;
    'timeout'?: number;
    'title'?: string;
    'variant'?: string;
    'withTimeout'?: boolean;
  }
  interface TButton extends JSXBase.HTMLAttributes<HTMLTButtonElement> {
    /**
    * (optional) Deselected button
    */
    'deselected'?: boolean;
    /**
    * (optional) Disabled button
    */
    'disabled'?: boolean;
    /**
    * (optional) Button size
    */
    'size'?: string;
    /**
    * (optional) Button theme
    */
    'theme'?: string;
    /**
    * (optional) Button variant
    */
    'variant'?: string;
  }
  interface TCard extends JSXBase.HTMLAttributes<HTMLTCardElement> {
    'deselected'?: boolean;
    'disabled'?: boolean;
    'size'?: string;
    'theme'?: string;
    'variant'?: string;
  }

  interface IntrinsicElements {
    't-alert': TAlert;
    't-button': TButton;
    't-card': TCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


