name: bernerslee
on:
  push:
    branches:
      - bernerslee

jobs:
  deploy-bernerslee:
    runs-on: ubuntu-latest
    environment: BERNERSLEE
    steps:
      - uses: actions/checkout@v2

      - name: Restore Lerna
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run Lerna bootstrap
        run: |
          yarn bootstrap

      - name: Build Components
        run: |
          cd packages/components
          yarn build

      - name: Build Storybook
        run: |
          cd packages/storybook-vue
          yarn build --quiet

      - name: ZIP Storybook
        run: |
          cd packages/storybook-vue/storybook-static
          zip -r deploy.zip .

      - name: Upload to S3
        run: |
          aws --region eu-central-1 s3 cp packages/storybook-vue/storybook-static/deploy.zip s3://scale-bernerslee/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
